### ISSUE TITLE
Compiler warnings: "address of a resource handle"

### ISSUE THREAD

**Issue by oscarbailey-xmos** [xmos/lib_spdif#30]
```
Compiling SpdifTransmit.xc
/home/oscar/sandboxes/usb_audio/lib_spdif/lib_spdif/src/SpdifTransmit.xc:861:29: warning: Taking the address of a resource handle, not the actual resource. Passing by (unsafe) value may be a better option [-Wunusual-code]
    out port * movable pp = &p_spdif;
                            ^~~~~~~~
Compiling spdif_rx.xc
/home/oscar/sandboxes/usb_audio/lib_spdif/lib_spdif/src/spdif_rx.xc:16:26: warning: Taking the address of a resource handle, not the actual resource. Passing by (unsafe) value may be a better option [-Wunusual-code]
  in port * movable pp = &p;
                         ^~
```

Found while compiling `sw_usb_audio`

**Comment by ed-xmos** [comment]
I just want to add a strong +1 to this issue. It adds unnecessary noise to the sw_usb_audio and lib_xua compilation. I'm sure this can be worked around.

**Comment by xross** [comment]
Couple of options 
- see if this a warning we can disable in the compiler
- use inline asm or similar (bit messy)
- bin the port re-use stuff

**Comment by xross** [comment]
My suggestion for a quick "fix". 

- Move void spdif_tx_reconfig_port(chanend c, out port p_spdif, const clock mclk) to separate file
- Apply -Wunusual-code to this file only

**Comment by xross** [comment]
https://github.com/xmos/lib_spdif/pull/68
